version: 0.2

env:
  variables:
    # This S3 stores the ECS Reference Architecture CloudFormation templates
    # so that they can be deployed via a button on the project GitHub README
    S3_BUCKET: "ecs-refarch-cloudformation"

phases:

  pre_build: 
    commands:
      - sed -i -e "s/ecs-refarch-cloudformation/${S3_BUCKET}/g" ./master.yaml
     # Validate all of the CloudFormation templates
      - chmod a+x ./tests/validate-templates.sh
      - ./tests/validate-templates.sh
 
  build:
    commands:
      - echo ${S3_BUCKET}
      # Sync the templates
      - aws s3 sync . s3://${S3_BUCKET}

